// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_settings`, `decode_thumb_blob`, `download_to_cache`, `from_json`, `open_url_checked`, `run_blocking`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `glaspen2_notify_settings_changed`

/// 当前设置。
Future<Settings?> getSettings() => RustLib.instance.api.crateApiGetSettings();

/// 写入一项设置。`value_json` 是 JSON 标量(`true` / `3` / `2.5`),
/// ObjC 侧按 key 解析,布尔/整数/小数共用一条通道。
Future<void> setSetting({required String key, required String valueJson}) =>
    RustLib.instance.api.crateApiSetSetting(key: key, valueJson: valueJson);

/// 设置面板「测试登录」:用当前已保存的涂鸦身份配置强制登录一次
/// (成功则缓存 token,后续 DraftInk/AppendMessages 立即携带身份)。
/// 返回空串 = 成功,否则为可读失败原因。
Future<String> testChatLogin() => RustLib.instance.api.crateApiTestChatLogin();

/// 设置变化推送流:面板订阅它,菜单/快捷键的改动能实时同步到 UI。
Stream<Settings> settingsChanged() =>
    RustLib.instance.api.crateApiSettingsChanged();

/// 活页本概览:每页的 id、尺寸和笔迹数。
Future<List<PageSummary>> listPages() =>
    RustLib.instance.api.crateApiListPages();

/// 批量缩略图:一次调用取回整屏(版本查询、缓存读取、缺失渲染都在 Rust 侧
/// 批量化)。没有笔迹的页不会出现在结果里。
Future<List<PageThumb>> pageThumbnails({
  required Int64List ids,
  required int maxSize,
}) => RustLib.instance.api.crateApiPageThumbnails(ids: ids, maxSize: maxSize);

/// 删除一页及其笔迹。
Future<bool> deletePage({required PlatformInt64 screenId}) =>
    RustLib.instance.api.crateApiDeletePage(screenId: screenId);

/// 导出单页 PNG(白底, 2x 采样)到桌面。
Future<bool> exportPagePng({required PlatformInt64 screenId}) =>
    RustLib.instance.api.crateApiExportPagePng(screenId: screenId);

/// 导出单页 SVG(内容包围盒)到桌面。
Future<bool> exportPageSvg({required PlatformInt64 screenId}) =>
    RustLib.instance.api.crateApiExportPageSvg(screenId: screenId);

/// 勾选的页合成单个 PDF(空列表 = 全部页)到桌面。
Future<bool> exportSelectedPdf({required Int64List ids}) =>
    RustLib.instance.api.crateApiExportSelectedPdf(ids: ids);

/// OCR 全文搜索: 返回匹配的页 id(升序)。查不到/无 OCR 结果为空。
Future<Int64List> ocrSearch({required String query}) =>
    RustLib.instance.api.crateApiOcrSearch(query: query);

/// 跳转到指定页继续绘画。
Future<void> navigateToPage({required PlatformInt64 screenId}) =>
    RustLib.instance.api.crateApiNavigateToPage(screenId: screenId);

/// 触发一个快捷键动作(与物理 ⌃⌘<key> 等价)。
Future<void> triggerHotkey({required String key}) =>
    RustLib.instance.api.crateApiTriggerHotkey(key: key);

/// 无限画布总览。`w`/`h` 小于 400 时按 1024×768 处理。空画布返回 None。
Future<CanvasPayload?> canvasOverview({
  required int w,
  required int h,
  required CanvasAction action,
}) => RustLib.instance.api.crateApiCanvasOverview(w: w, h: h, action: action);

/// 当前镜头状态(无限画布)。
Future<LensState> getLens() => RustLib.instance.api.crateApiGetLens();

/// 页号跟随:当前页在所有页中的序号(1 起)。
Future<BigInt> getPageOrdinal() =>
    RustLib.instance.api.crateApiGetPageOrdinal();

/// 把全部数据备份到桌面。产出单个 .db 文件(一致快照), 换机时可直接替换
/// glaspen2.db 使用。
Future<BackupOutcome> backupNow() => RustLib.instance.api.crateApiBackupNow();

/// 从桌面上最新的备份**合并**恢复: 不会删除备份之后新画的页/笔迹, 同名 id
/// 以备份为准。恢复后需要重启才能看到覆盖层上的变化。
Future<BackupOutcome> restoreLatestBackup() =>
    RustLib.instance.api.crateApiRestoreLatestBackup();

/// 当前版本号(与发布物一致,取自 Cargo.toml)。
Future<String> appVersion() => RustLib.instance.api.crateApiAppVersion();

/// 检查 GitHub Releases 上的最新正式版(手动触发;阻塞网络放在独立线程,
/// 见 [`run_blocking`])。
Future<UpdateCheck> checkUpdate() => RustLib.instance.api.crateApiCheckUpdate();

/// 下载最新安装包到缓存,**流式推进度**。
///
/// 重新查一次 release 并由 Rust 侧挑本平台的包(与检查结果解耦,不依赖
/// UI 传参)。已存在且校验通过的包直接复用。取消订阅流即取消下载:
/// 下一帧推不进去 → 回调返回 false → 删除 `.part`。
Stream<UpdateProgress> downloadUpdate() =>
    RustLib.instance.api.crateApiDownloadUpdate();

/// 解包缓存里最新的 DMG(挂载 → ditto → 卸载 → 验签 → 剥 quarantine)。
/// 在主程序退出前完成,失败原因能直接显示在面板上。`tag` 用于命名暂存目录。
Future<UpdateOutcome> stageUpdate({required String tag}) =>
    RustLib.instance.api.crateApiStageUpdate(tag: tag);

/// 启动 `--updater` 帮手并退出本程序(用户点「立即重启更新」)。
///
/// **成功的路径不返回**:`shim::hotkey("Q")` → `[NSApp terminate:]` 会在
/// 主线程把进程结束掉;只有每一步失败才回到这里,带着 `ok=false`。
Future<UpdateOutcome> applyUpdate() =>
    RustLib.instance.api.crateApiApplyUpdate();

/// 用系统默认浏览器打开一个 http(s) URL(「打开下载页」按钮)。
Future<void> openUrl({required String url}) =>
    RustLib.instance.api.crateApiOpenUrl(url: url);

/// 导出当前页为 PDF。
Future<bool> exportPdf() => RustLib.instance.api.crateApiExportPdf();

/// 导出动画 GIF 并复制到剪贴板。
Future<bool> exportAnimatedGif() =>
    RustLib.instance.api.crateApiExportAnimatedGif();

/// 备份/回导结果:成败 + 给用户看的一句话(成功时是文件路径)。
class BackupOutcome {
  final bool ok;
  final String message;

  const BackupOutcome({required this.ok, required this.message});

  @override
  int get hashCode => ok.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupOutcome &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          message == other.message;
}

/// 镜头动作。
enum CanvasAction {
  /// 只取当前总览
  current,

  /// 镜头回原点 + 100%
  home,

  /// 镜头居中到内容包围盒
  center,

  /// 清空内容 + 镜头回原点
  new_,
}

/// 总览载荷:PNG + 当前视口矩形 [x, y, w, h]。
class CanvasPayload {
  final Uint8List png;
  final Float64List rect;

  const CanvasPayload({required this.png, required this.rect});

  @override
  int get hashCode => png.hashCode ^ rect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CanvasPayload &&
          runtimeType == other.runtimeType &&
          png == other.png &&
          rect == other.rect;
}

class LensState {
  final PlatformInt64 pageId;
  final double panX;
  final double panY;
  final double zoom;

  const LensState({
    required this.pageId,
    required this.panX,
    required this.panY,
    required this.zoom,
  });

  @override
  int get hashCode =>
      pageId.hashCode ^ panX.hashCode ^ panY.hashCode ^ zoom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LensState &&
          runtimeType == other.runtimeType &&
          pageId == other.pageId &&
          panX == other.panX &&
          panY == other.panY &&
          zoom == other.zoom;
}

class PageSummary {
  final PlatformInt64 id;
  final int width;
  final int height;
  final BigInt strokeCount;

  const PageSummary({
    required this.id,
    required this.width,
    required this.height,
    required this.strokeCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ width.hashCode ^ height.hashCode ^ strokeCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          width == other.width &&
          height == other.height &&
          strokeCount == other.strokeCount;
}

/// 一页的缩略图。
class PageThumb {
  final PlatformInt64 id;
  final Uint8List png;

  const PageThumb({required this.id, required this.png});

  @override
  int get hashCode => id.hashCode ^ png.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageThumb &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          png == other.png;
}

/// 设置快照。字段与旧 MethodChannel 字典一一对应,Dart 侧 `_FrbBridge`
/// 会转回原来的 Map 形状,UI 代码无需改动。
class Settings {
  final int color;
  final int width;
  final bool rainbow;
  final bool launchAtLogin;
  final bool frostedGlass;
  final bool grid;
  final bool gridFollowStrokes;
  final bool pressureMonitor;
  final bool outline;
  final bool infiniteCanvas;
  final bool minimap;
  final double gridSize;
  final int gridDivider;
  final int flipEffect;
  final int gifFps;
  final double gifResolution;
  final double gifSpeed;
  final int gifEndMode;
  final String chatApiBase;
  final String chatUser;
  final bool chatHasPassword;
  final bool chatIntegration;
  final bool showFreeCanvas;
  final bool shareCanvas;

  const Settings({
    required this.color,
    required this.width,
    required this.rainbow,
    required this.launchAtLogin,
    required this.frostedGlass,
    required this.grid,
    required this.gridFollowStrokes,
    required this.pressureMonitor,
    required this.outline,
    required this.infiniteCanvas,
    required this.minimap,
    required this.gridSize,
    required this.gridDivider,
    required this.flipEffect,
    required this.gifFps,
    required this.gifResolution,
    required this.gifSpeed,
    required this.gifEndMode,
    required this.chatApiBase,
    required this.chatUser,
    required this.chatHasPassword,
    required this.chatIntegration,
    required this.showFreeCanvas,
    required this.shareCanvas,
  });

  @override
  int get hashCode =>
      color.hashCode ^
      width.hashCode ^
      rainbow.hashCode ^
      launchAtLogin.hashCode ^
      frostedGlass.hashCode ^
      grid.hashCode ^
      gridFollowStrokes.hashCode ^
      pressureMonitor.hashCode ^
      outline.hashCode ^
      infiniteCanvas.hashCode ^
      minimap.hashCode ^
      gridSize.hashCode ^
      gridDivider.hashCode ^
      flipEffect.hashCode ^
      gifFps.hashCode ^
      gifResolution.hashCode ^
      gifSpeed.hashCode ^
      gifEndMode.hashCode ^
      chatApiBase.hashCode ^
      chatUser.hashCode ^
      chatHasPassword.hashCode ^
      chatIntegration.hashCode ^
      showFreeCanvas.hashCode ^
      shareCanvas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          color == other.color &&
          width == other.width &&
          rainbow == other.rainbow &&
          launchAtLogin == other.launchAtLogin &&
          frostedGlass == other.frostedGlass &&
          grid == other.grid &&
          gridFollowStrokes == other.gridFollowStrokes &&
          pressureMonitor == other.pressureMonitor &&
          outline == other.outline &&
          infiniteCanvas == other.infiniteCanvas &&
          minimap == other.minimap &&
          gridSize == other.gridSize &&
          gridDivider == other.gridDivider &&
          flipEffect == other.flipEffect &&
          gifFps == other.gifFps &&
          gifResolution == other.gifResolution &&
          gifSpeed == other.gifSpeed &&
          gifEndMode == other.gifEndMode &&
          chatApiBase == other.chatApiBase &&
          chatUser == other.chatUser &&
          chatHasPassword == other.chatHasPassword &&
          chatIntegration == other.chatIntegration &&
          showFreeCanvas == other.showFreeCanvas &&
          shareCanvas == other.shareCanvas;
}

/// release 里的一个安装包(挑包下载用)。
class UpdateAsset {
  final String name;
  final String url;

  /// 字节数(进度条总量;GitHub 可能给 0)。
  final BigInt size;

  /// sha256(小写无前缀);GitHub 没给 `digest` 时为 None。
  final String? sha256;

  const UpdateAsset({
    required this.name,
    required this.url,
    required this.size,
    this.sha256,
  });

  @override
  int get hashCode =>
      name.hashCode ^ url.hashCode ^ size.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateAsset &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          size == other.size &&
          sha256 == other.sha256;
}

/// 「检查更新」结果。`ok=false` 时 `error` 是给用户看的原因;
/// `has_update=true` 时 `url` 指向最新发布的下载页。
class UpdateCheck {
  /// 检查是否成功(网络/解析)。
  final bool ok;

  /// 当前运行的版本(编译时取自 Cargo.toml),检查失败时也总有值。
  final String current;

  /// GitHub 最新正式版 tag(如 `v0.5.1`);失败时为空。
  final String latest;

  /// 最新版本是否比当前新。
  final bool hasUpdate;

  /// 最新发布的页面地址;没有更新或检查失败时为空。
  final String url;

  /// 失败原因;成功时为空。
  final String error;

  /// release notes(确认对话框展示;可能为空)。
  final String notes;

  /// 安装包资产;挑不到本平台的包时 `下载并更新` 应降级为打开下载页。
  final List<UpdateAsset> assets;

  const UpdateCheck({
    required this.ok,
    required this.current,
    required this.latest,
    required this.hasUpdate,
    required this.url,
    required this.error,
    required this.notes,
    required this.assets,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      current.hashCode ^
      latest.hashCode ^
      hasUpdate.hashCode ^
      url.hashCode ^
      error.hashCode ^
      notes.hashCode ^
      assets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateCheck &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          current == other.current &&
          latest == other.latest &&
          hasUpdate == other.hasUpdate &&
          url == other.url &&
          error == other.error &&
          notes == other.notes &&
          assets == other.assets;
}

/// 解包 / 退出替换这类"一句话结果"。
class UpdateOutcome {
  final bool ok;

  /// 成功时是给用户看的路径,失败时是原因。
  final String message;

  const UpdateOutcome({required this.ok, required this.message});

  @override
  int get hashCode => ok.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateOutcome &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          message == other.message;
}

/// 下载进度帧(最后一帧 `done=true`;`error` 非空 = 失败)。
class UpdateProgress {
  final BigInt received;
  final BigInt total;
  final bool done;
  final String error;

  /// 成功时 = 下载完成的安装包路径。
  final String path;

  const UpdateProgress({
    required this.received,
    required this.total,
    required this.done,
    required this.error,
    required this.path,
  });

  @override
  int get hashCode =>
      received.hashCode ^
      total.hashCode ^
      done.hashCode ^
      error.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateProgress &&
          runtimeType == other.runtimeType &&
          received == other.received &&
          total == other.total &&
          done == other.done &&
          error == other.error &&
          path == other.path;
}
