// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 活页本概览：每页的 id 和笔迹数（用于列表展示 + 空页标识）。
Future<List<PageSummary>> listPages() =>
    RustLib.instance.api.crateApiListPages();

/// 当前镜头状态（无限画布）。
Future<LensState> getLens() => RustLib.instance.api.crateApiGetLens();

/// 页号跟随：当前页在所有页中的序号（1 起）。
Future<BigInt> getPageOrdinal() =>
    RustLib.instance.api.crateApiGetPageOrdinal();

class LensState {
  final PlatformInt64 pageId;
  final double panX;
  final double panY;
  final double zoom;

  const LensState({
    required this.pageId,
    required this.panX,
    required this.panY,
    required this.zoom,
  });

  @override
  int get hashCode =>
      pageId.hashCode ^ panX.hashCode ^ panY.hashCode ^ zoom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LensState &&
          runtimeType == other.runtimeType &&
          pageId == other.pageId &&
          panX == other.panX &&
          panY == other.panY &&
          zoom == other.zoom;
}

class PageSummary {
  final PlatformInt64 id;
  final int width;
  final int height;
  final BigInt strokeCount;

  const PageSummary({
    required this.id,
    required this.width,
    required this.height,
    required this.strokeCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ width.hashCode ^ height.hashCode ^ strokeCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          width == other.width &&
          height == other.height &&
          strokeCount == other.strokeCount;
}
