// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1829997856;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'glaspen2',
        ioDirectory: '../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAppVersion();

  Future<UpdateOutcome> crateApiApplyUpdate();

  Future<BackupOutcome> crateApiBackupNow();

  Future<CanvasPayload?> crateApiCanvasOverview({
    required int w,
    required int h,
    required CanvasAction action,
  });

  Future<UpdateCheck> crateApiCheckUpdate();

  Future<bool> crateApiDeletePage({required PlatformInt64 screenId});

  Stream<UpdateProgress> crateApiDownloadUpdate();

  Future<bool> crateApiExportAnimatedGif();

  Future<bool> crateApiExportPagePng({required PlatformInt64 screenId});

  Future<bool> crateApiExportPageSvg({required PlatformInt64 screenId});

  Future<bool> crateApiExportPdf();

  Future<bool> crateApiExportSelectedPdf({required Int64List ids});

  Future<LensState> crateApiGetLens();

  Future<BigInt> crateApiGetPageOrdinal();

  Future<Settings?> crateApiGetSettings();

  Future<List<PageSummary>> crateApiListPages();

  Future<void> crateApiNavigateToPage({required PlatformInt64 screenId});

  Future<Int64List> crateApiOcrSearch({required String query});

  Future<void> crateApiOpenUrl({required String url});

  Future<List<PageThumb>> crateApiPageThumbnails({
    required Int64List ids,
    required int maxSize,
  });

  Future<BackupOutcome> crateApiRestoreLatestBackup();

  Future<void> crateApiSetSetting({
    required String key,
    required String valueJson,
  });

  Stream<Settings> crateApiSettingsChanged();

  Future<UpdateOutcome> crateApiStageUpdate({required String tag});

  Future<String> crateApiTestChatLogin();

  Future<void> crateApiTriggerHotkey({required String key});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAppVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppVersionConstMeta =>
      const TaskConstMeta(debugName: "app_version", argNames: []);

  @override
  Future<UpdateOutcome> crateApiApplyUpdate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApplyUpdateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplyUpdateConstMeta =>
      const TaskConstMeta(debugName: "apply_update", argNames: []);

  @override
  Future<BackupOutcome> crateApiBackupNow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_backup_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBackupNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBackupNowConstMeta =>
      const TaskConstMeta(debugName: "backup_now", argNames: []);

  @override
  Future<CanvasPayload?> crateApiCanvasOverview({
    required int w,
    required int h,
    required CanvasAction action,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(w, serializer);
          sse_encode_i_32(h, serializer);
          sse_encode_canvas_action(action, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_canvas_payload,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCanvasOverviewConstMeta,
        argValues: [w, h, action],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCanvasOverviewConstMeta => const TaskConstMeta(
    debugName: "canvas_overview",
    argNames: ["w", "h", "action"],
  );

  @override
  Future<UpdateCheck> crateApiCheckUpdate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_check,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCheckUpdateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckUpdateConstMeta =>
      const TaskConstMeta(debugName: "check_update", argNames: []);

  @override
  Future<bool> crateApiDeletePage({required PlatformInt64 screenId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(screenId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeletePageConstMeta,
        argValues: [screenId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeletePageConstMeta =>
      const TaskConstMeta(debugName: "delete_page", argNames: ["screenId"]);

  @override
  Stream<UpdateProgress> crateApiDownloadUpdate() {
    final sink = RustStreamSink<UpdateProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_update_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiDownloadUpdateConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloadUpdateConstMeta =>
      const TaskConstMeta(debugName: "download_update", argNames: ["sink"]);

  @override
  Future<bool> crateApiExportAnimatedGif() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportAnimatedGifConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportAnimatedGifConstMeta =>
      const TaskConstMeta(debugName: "export_animated_gif", argNames: []);

  @override
  Future<bool> crateApiExportPagePng({required PlatformInt64 screenId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(screenId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportPagePngConstMeta,
        argValues: [screenId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportPagePngConstMeta =>
      const TaskConstMeta(debugName: "export_page_png", argNames: ["screenId"]);

  @override
  Future<bool> crateApiExportPageSvg({required PlatformInt64 screenId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(screenId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportPageSvgConstMeta,
        argValues: [screenId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportPageSvgConstMeta =>
      const TaskConstMeta(debugName: "export_page_svg", argNames: ["screenId"]);

  @override
  Future<bool> crateApiExportPdf() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportPdfConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportPdfConstMeta =>
      const TaskConstMeta(debugName: "export_pdf", argNames: []);

  @override
  Future<bool> crateApiExportSelectedPdf({required Int64List ids}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_64_strict(ids, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExportSelectedPdfConstMeta,
        argValues: [ids],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportSelectedPdfConstMeta =>
      const TaskConstMeta(debugName: "export_selected_pdf", argNames: ["ids"]);

  @override
  Future<LensState> crateApiGetLens() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lens_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLensConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLensConstMeta =>
      const TaskConstMeta(debugName: "get_lens", argNames: []);

  @override
  Future<BigInt> crateApiGetPageOrdinal() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetPageOrdinalConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPageOrdinalConstMeta =>
      const TaskConstMeta(debugName: "get_page_ordinal", argNames: []);

  @override
  Future<Settings?> crateApiGetSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_settings", argNames: []);

  @override
  Future<List<PageSummary>> crateApiListPages() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiListPagesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListPagesConstMeta =>
      const TaskConstMeta(debugName: "list_pages", argNames: []);

  @override
  Future<void> crateApiNavigateToPage({required PlatformInt64 screenId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(screenId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNavigateToPageConstMeta,
        argValues: [screenId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNavigateToPageConstMeta => const TaskConstMeta(
    debugName: "navigate_to_page",
    argNames: ["screenId"],
  );

  @override
  Future<Int64List> crateApiOcrSearch({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOcrSearchConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOcrSearchConstMeta =>
      const TaskConstMeta(debugName: "ocr_search", argNames: ["query"]);

  @override
  Future<void> crateApiOpenUrl({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOpenUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenUrlConstMeta =>
      const TaskConstMeta(debugName: "open_url", argNames: ["url"]);

  @override
  Future<List<PageThumb>> crateApiPageThumbnails({
    required Int64List ids,
    required int maxSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_64_strict(ids, serializer);
          sse_encode_i_32(maxSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_thumb,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPageThumbnailsConstMeta,
        argValues: [ids, maxSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPageThumbnailsConstMeta => const TaskConstMeta(
    debugName: "page_thumbnails",
    argNames: ["ids", "maxSize"],
  );

  @override
  Future<BackupOutcome> crateApiRestoreLatestBackup() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_backup_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRestoreLatestBackupConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestoreLatestBackupConstMeta =>
      const TaskConstMeta(debugName: "restore_latest_backup", argNames: []);

  @override
  Future<void> crateApiSetSetting({
    required String key,
    required String valueJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(valueJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetSettingConstMeta,
        argValues: [key, valueJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSettingConstMeta => const TaskConstMeta(
    debugName: "set_setting",
    argNames: ["key", "valueJson"],
  );

  @override
  Stream<Settings> crateApiSettingsChanged() {
    final sink = RustStreamSink<Settings>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_settings_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 23,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSettingsChangedConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSettingsChangedConstMeta =>
      const TaskConstMeta(debugName: "settings_changed", argNames: ["sink"]);

  @override
  Future<UpdateOutcome> crateApiStageUpdate({required String tag}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tag, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStageUpdateConstMeta,
        argValues: [tag],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStageUpdateConstMeta =>
      const TaskConstMeta(debugName: "stage_update", argNames: ["tag"]);

  @override
  Future<String> crateApiTestChatLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTestChatLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTestChatLoginConstMeta =>
      const TaskConstMeta(debugName: "test_chat_login", argNames: []);

  @override
  Future<void> crateApiTriggerHotkey({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTriggerHotkeyConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTriggerHotkeyConstMeta =>
      const TaskConstMeta(debugName: "trigger_hotkey", argNames: ["key"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Settings> dco_decode_StreamSink_settings_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<UpdateProgress> dco_decode_StreamSink_update_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BackupOutcome dco_decode_backup_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BackupOutcome(
      ok: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CanvasPayload dco_decode_box_autoadd_canvas_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_canvas_payload(raw);
  }

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings(raw);
  }

  @protected
  CanvasAction dco_decode_canvas_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CanvasAction.values[raw as int];
  }

  @protected
  CanvasPayload dco_decode_canvas_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CanvasPayload(
      png: dco_decode_list_prim_u_8_strict(arr[0]),
      rect: dco_decode_list_prim_f_64_strict(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LensState dco_decode_lens_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LensState(
      pageId: dco_decode_i_64(arr[0]),
      panX: dco_decode_f_64(arr[1]),
      panY: dco_decode_f_64(arr[2]),
      zoom: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  List<PageSummary> dco_decode_list_page_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_summary).toList();
  }

  @protected
  List<PageThumb> dco_decode_list_page_thumb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_thumb).toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<UpdateAsset> dco_decode_list_update_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_update_asset).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CanvasPayload? dco_decode_opt_box_autoadd_canvas_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_canvas_payload(raw);
  }

  @protected
  Settings? dco_decode_opt_box_autoadd_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_settings(raw);
  }

  @protected
  PageSummary dco_decode_page_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PageSummary(
      id: dco_decode_i_64(arr[0]),
      width: dco_decode_i_32(arr[1]),
      height: dco_decode_i_32(arr[2]),
      strokeCount: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  PageThumb dco_decode_page_thumb(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PageThumb(
      id: dco_decode_i_64(arr[0]),
      png: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  Settings dco_decode_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 24)
      throw Exception('unexpected arr length: expect 24 but see ${arr.length}');
    return Settings(
      color: dco_decode_i_32(arr[0]),
      width: dco_decode_i_32(arr[1]),
      rainbow: dco_decode_bool(arr[2]),
      launchAtLogin: dco_decode_bool(arr[3]),
      frostedGlass: dco_decode_bool(arr[4]),
      grid: dco_decode_bool(arr[5]),
      gridFollowStrokes: dco_decode_bool(arr[6]),
      pressureMonitor: dco_decode_bool(arr[7]),
      outline: dco_decode_bool(arr[8]),
      infiniteCanvas: dco_decode_bool(arr[9]),
      minimap: dco_decode_bool(arr[10]),
      gridSize: dco_decode_f_64(arr[11]),
      gridDivider: dco_decode_i_32(arr[12]),
      flipEffect: dco_decode_i_32(arr[13]),
      gifFps: dco_decode_i_32(arr[14]),
      gifResolution: dco_decode_f_64(arr[15]),
      gifSpeed: dco_decode_f_64(arr[16]),
      gifEndMode: dco_decode_i_32(arr[17]),
      chatApiBase: dco_decode_String(arr[18]),
      chatUser: dco_decode_String(arr[19]),
      chatHasPassword: dco_decode_bool(arr[20]),
      chatIntegration: dco_decode_bool(arr[21]),
      showFreeCanvas: dco_decode_bool(arr[22]),
      shareCanvas: dco_decode_bool(arr[23]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateAsset dco_decode_update_asset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UpdateAsset(
      name: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      sha256: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  UpdateCheck dco_decode_update_check(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return UpdateCheck(
      ok: dco_decode_bool(arr[0]),
      current: dco_decode_String(arr[1]),
      latest: dco_decode_String(arr[2]),
      hasUpdate: dco_decode_bool(arr[3]),
      url: dco_decode_String(arr[4]),
      error: dco_decode_String(arr[5]),
      notes: dco_decode_String(arr[6]),
      assets: dco_decode_list_update_asset(arr[7]),
    );
  }

  @protected
  UpdateOutcome dco_decode_update_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return UpdateOutcome(
      ok: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  UpdateProgress dco_decode_update_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return UpdateProgress(
      received: dco_decode_u_64(arr[0]),
      total: dco_decode_u_64(arr[1]),
      done: dco_decode_bool(arr[2]),
      error: dco_decode_String(arr[3]),
      path: dco_decode_String(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Settings> sse_decode_StreamSink_settings_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<UpdateProgress> sse_decode_StreamSink_update_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BackupOutcome sse_decode_backup_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BackupOutcome(ok: var_ok, message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CanvasPayload sse_decode_box_autoadd_canvas_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_canvas_payload(deserializer));
  }

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings(deserializer));
  }

  @protected
  CanvasAction sse_decode_canvas_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CanvasAction.values[inner];
  }

  @protected
  CanvasPayload sse_decode_canvas_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_png = sse_decode_list_prim_u_8_strict(deserializer);
    var var_rect = sse_decode_list_prim_f_64_strict(deserializer);
    return CanvasPayload(png: var_png, rect: var_rect);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LensState sse_decode_lens_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageId = sse_decode_i_64(deserializer);
    var var_panX = sse_decode_f_64(deserializer);
    var var_panY = sse_decode_f_64(deserializer);
    var var_zoom = sse_decode_f_64(deserializer);
    return LensState(
      pageId: var_pageId,
      panX: var_panX,
      panY: var_panY,
      zoom: var_zoom,
    );
  }

  @protected
  List<PageSummary> sse_decode_list_page_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageThumb> sse_decode_list_page_thumb(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageThumb>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_thumb(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<UpdateAsset> sse_decode_list_update_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UpdateAsset>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_update_asset(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CanvasPayload? sse_decode_opt_box_autoadd_canvas_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_canvas_payload(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Settings? sse_decode_opt_box_autoadd_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_settings(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageSummary sse_decode_page_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    var var_strokeCount = sse_decode_u_64(deserializer);
    return PageSummary(
      id: var_id,
      width: var_width,
      height: var_height,
      strokeCount: var_strokeCount,
    );
  }

  @protected
  PageThumb sse_decode_page_thumb(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_png = sse_decode_list_prim_u_8_strict(deserializer);
    return PageThumb(id: var_id, png: var_png);
  }

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_color = sse_decode_i_32(deserializer);
    var var_width = sse_decode_i_32(deserializer);
    var var_rainbow = sse_decode_bool(deserializer);
    var var_launchAtLogin = sse_decode_bool(deserializer);
    var var_frostedGlass = sse_decode_bool(deserializer);
    var var_grid = sse_decode_bool(deserializer);
    var var_gridFollowStrokes = sse_decode_bool(deserializer);
    var var_pressureMonitor = sse_decode_bool(deserializer);
    var var_outline = sse_decode_bool(deserializer);
    var var_infiniteCanvas = sse_decode_bool(deserializer);
    var var_minimap = sse_decode_bool(deserializer);
    var var_gridSize = sse_decode_f_64(deserializer);
    var var_gridDivider = sse_decode_i_32(deserializer);
    var var_flipEffect = sse_decode_i_32(deserializer);
    var var_gifFps = sse_decode_i_32(deserializer);
    var var_gifResolution = sse_decode_f_64(deserializer);
    var var_gifSpeed = sse_decode_f_64(deserializer);
    var var_gifEndMode = sse_decode_i_32(deserializer);
    var var_chatApiBase = sse_decode_String(deserializer);
    var var_chatUser = sse_decode_String(deserializer);
    var var_chatHasPassword = sse_decode_bool(deserializer);
    var var_chatIntegration = sse_decode_bool(deserializer);
    var var_showFreeCanvas = sse_decode_bool(deserializer);
    var var_shareCanvas = sse_decode_bool(deserializer);
    return Settings(
      color: var_color,
      width: var_width,
      rainbow: var_rainbow,
      launchAtLogin: var_launchAtLogin,
      frostedGlass: var_frostedGlass,
      grid: var_grid,
      gridFollowStrokes: var_gridFollowStrokes,
      pressureMonitor: var_pressureMonitor,
      outline: var_outline,
      infiniteCanvas: var_infiniteCanvas,
      minimap: var_minimap,
      gridSize: var_gridSize,
      gridDivider: var_gridDivider,
      flipEffect: var_flipEffect,
      gifFps: var_gifFps,
      gifResolution: var_gifResolution,
      gifSpeed: var_gifSpeed,
      gifEndMode: var_gifEndMode,
      chatApiBase: var_chatApiBase,
      chatUser: var_chatUser,
      chatHasPassword: var_chatHasPassword,
      chatIntegration: var_chatIntegration,
      showFreeCanvas: var_showFreeCanvas,
      shareCanvas: var_shareCanvas,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateAsset sse_decode_update_asset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_sha256 = sse_decode_opt_String(deserializer);
    return UpdateAsset(
      name: var_name,
      url: var_url,
      size: var_size,
      sha256: var_sha256,
    );
  }

  @protected
  UpdateCheck sse_decode_update_check(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_current = sse_decode_String(deserializer);
    var var_latest = sse_decode_String(deserializer);
    var var_hasUpdate = sse_decode_bool(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_error = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_assets = sse_decode_list_update_asset(deserializer);
    return UpdateCheck(
      ok: var_ok,
      current: var_current,
      latest: var_latest,
      hasUpdate: var_hasUpdate,
      url: var_url,
      error: var_error,
      notes: var_notes,
      assets: var_assets,
    );
  }

  @protected
  UpdateOutcome sse_decode_update_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return UpdateOutcome(ok: var_ok, message: var_message);
  }

  @protected
  UpdateProgress sse_decode_update_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_received = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    var var_done = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    return UpdateProgress(
      received: var_received,
      total: var_total,
      done: var_done,
      error: var_error,
      path: var_path,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_settings_Sse(
    RustStreamSink<Settings> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_update_progress_Sse(
    RustStreamSink<UpdateProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_backup_outcome(BackupOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_canvas_payload(
    CanvasPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_canvas_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings(
    Settings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings(self, serializer);
  }

  @protected
  void sse_encode_canvas_action(CanvasAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_canvas_payload(CanvasPayload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.png, serializer);
    sse_encode_list_prim_f_64_strict(self.rect, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_lens_state(LensState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.pageId, serializer);
    sse_encode_f_64(self.panX, serializer);
    sse_encode_f_64(self.panY, serializer);
    sse_encode_f_64(self.zoom, serializer);
  }

  @protected
  void sse_encode_list_page_summary(
    List<PageSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_thumb(
    List<PageThumb> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_thumb(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_update_asset(
    List<UpdateAsset> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_update_asset(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_canvas_payload(
    CanvasPayload? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_canvas_payload(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_settings(
    Settings? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_settings(self, serializer);
    }
  }

  @protected
  void sse_encode_page_summary(PageSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
    sse_encode_u_64(self.strokeCount, serializer);
  }

  @protected
  void sse_encode_page_thumb(PageThumb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_list_prim_u_8_strict(self.png, serializer);
  }

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.color, serializer);
    sse_encode_i_32(self.width, serializer);
    sse_encode_bool(self.rainbow, serializer);
    sse_encode_bool(self.launchAtLogin, serializer);
    sse_encode_bool(self.frostedGlass, serializer);
    sse_encode_bool(self.grid, serializer);
    sse_encode_bool(self.gridFollowStrokes, serializer);
    sse_encode_bool(self.pressureMonitor, serializer);
    sse_encode_bool(self.outline, serializer);
    sse_encode_bool(self.infiniteCanvas, serializer);
    sse_encode_bool(self.minimap, serializer);
    sse_encode_f_64(self.gridSize, serializer);
    sse_encode_i_32(self.gridDivider, serializer);
    sse_encode_i_32(self.flipEffect, serializer);
    sse_encode_i_32(self.gifFps, serializer);
    sse_encode_f_64(self.gifResolution, serializer);
    sse_encode_f_64(self.gifSpeed, serializer);
    sse_encode_i_32(self.gifEndMode, serializer);
    sse_encode_String(self.chatApiBase, serializer);
    sse_encode_String(self.chatUser, serializer);
    sse_encode_bool(self.chatHasPassword, serializer);
    sse_encode_bool(self.chatIntegration, serializer);
    sse_encode_bool(self.showFreeCanvas, serializer);
    sse_encode_bool(self.shareCanvas, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_asset(UpdateAsset self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_opt_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_update_check(UpdateCheck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.current, serializer);
    sse_encode_String(self.latest, serializer);
    sse_encode_bool(self.hasUpdate, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.error, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_list_update_asset(self.assets, serializer);
  }

  @protected
  void sse_encode_update_outcome(UpdateOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_update_progress(
    UpdateProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.received, serializer);
    sse_encode_u_64(self.total, serializer);
    sse_encode_bool(self.done, serializer);
    sse_encode_String(self.error, serializer);
    sse_encode_String(self.path, serializer);
  }
}
