use std::sync::Mutex;
use windows::Win32::Foundation::*;
use windows::Win32::UI::WindowsAndMessaging::*;
use windows::Win32::System::LibraryLoader::GetModuleHandleW;

use super::overlay;
use super::render;

static HOOK_HANDLE: Mutex<isize> = Mutex::new(0);
static HOOK_HWND: Mutex<isize> = Mutex::new(0);
static mut PEN_DRAWING: bool = false;
static mut STROKE_COLOR: (f64, f64, f64) = (1.0, 0.0, 0.0);

/// Install the global low-level mouse hook on the current thread.
pub fn install_hook(hwnd: HWND) {
    let hmodule = unsafe { GetModuleHandleW(None).unwrap() };
    let instance = HINSTANCE(hmodule.0);
    let hook = unsafe {
        SetWindowsHookExW(WH_MOUSE_LL, Some(mouse_hook_proc), instance, 0).unwrap()
    };
    let mut h = HOOK_HANDLE.lock().unwrap();
    *h = hook.0 as isize;
    set_hook_hwnd(hwnd);
}

/// Uninstall the mouse hook.
pub fn uninstall_hook() {
    let h = HOOK_HANDLE.lock().unwrap();
    if *h != 0 {
        unsafe {
            let hook = HHOOK(*h as *mut _);
            UnhookWindowsHookEx(hook).ok();
        }
    }
    unsafe {
        if PEN_DRAWING {
            ShowCursor(TRUE);
            PEN_DRAWING = false;
        }
    }
}

fn set_hook_hwnd(hwnd: HWND) {
    let mut h = HOOK_HWND.lock().unwrap();
    *h = hwnd.0 as isize;
}

fn get_hook_hwnd() -> Option<HWND> {
    let h = HOOK_HWND.lock().unwrap();
    if *h == 0 {
        None
    } else {
        Some(HWND(*h as *mut _))
    }
}

/// Check if an event was generated by a pen/tablet.
fn is_pen_event(extra_info: usize) -> bool {
    if extra_info == 0 {
        return false;
    }
    let val = extra_info as u32;
    // High-bit patterns common with tablet pen drivers (Huion, Wacom)
    if val > 0x100 {
        return true;
    }
    false
}

/// Estimate pressure from extra_info (rough heuristic).
fn estimate_pressure(_extra_info: usize) -> f64 {
    // TODO: Parse raw input for actual pressure values.
    0.5
}

/// Sample screen color at (x, y) and return the inverted color.
fn sample_screen_inverse(x: f64, y: f64) -> (f64, f64, f64) {
    unsafe {
        use windows::Win32::Graphics::Gdi::{GetDC, ReleaseDC, GetPixel};
        let hdc = GetDC(None);
        if hdc.is_invalid() { return (1.0, 1.0, 1.0); }
        let color = GetPixel(hdc, x as i32, y as i32);
        ReleaseDC(None, hdc);
        if color.is_invalid() { return (1.0, 1.0, 1.0); }
        let r = (color.0 & 0xFF) as f64 / 255.0;
        let g = ((color.0 >> 8) & 0xFF) as f64 / 255.0;
        let b = ((color.0 >> 16) & 0xFF) as f64 / 255.0;
        (1.0 - r, 1.0 - g, 1.0 - b)
    }
}

/// Draw all smoothed points from the modeler buffer onto the surface.
fn draw_modeler_buffer(surface: &crate::cairo::ImageSurface, r: f64, g: f64, b: f64) {
    let count = crate::glaspen2_modeler_point_count();
    if count < 1 { return; }

    let mut prev_x = 0.0f64;
    let mut prev_y = 0.0f64;

    for i in 0..count {
        let mut px = 0.0f64;
        let mut py = 0.0f64;
        let mut pw = 0.0f64;
        crate::glaspen2_modeler_get_point(i, &mut px, &mut py, &mut pw);

        if i == 0 {
            render::pen_draw(surface, px, py, pw, r, g, b, 0.0, 0.0, false);
        } else {
            render::pen_draw(surface, px, py, pw, r, g, b, prev_x, prev_y, true);
        }
        prev_x = px;
        prev_y = py;
    }

    crate::glaspen2_modeler_clear_buffer();
}

unsafe extern "system" fn mouse_hook_proc(code: i32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    if code < 0 {
        return CallNextHookEx(None, code, wparam, lparam);
    }

    let hwnd = match get_hook_hwnd() {
        Some(h) => h,
        None => return CallNextHookEx(None, code, wparam, lparam),
    };

    let data = match overlay::get_overlay_data(hwnd) {
        Some(d) => d,
        None => return CallNextHookEx(None, code, wparam, lparam),
    };

    let hook_struct = &*(lparam.0 as *const MSLLHOOKSTRUCT);
    let extra_info = hook_struct.dwExtraInfo;
    let is_pen = is_pen_event(extra_info);
    let msg = wparam.0 as u32;
    let x = hook_struct.pt.x as f64;
    let y = hook_struct.pt.y as f64;
    let timestamp = hook_struct.time as f64 / 1000.0; // ms → seconds

    // --- Phase 1: Read/modify state under lock, collect modeler params ---
    let mut modeler_action: Option<ModelerAction> = None;
    let mut pen_color: (f64, f64, f64) = (0.0, 0.0, 0.0);
    let mut width_scale = 1.0;
    let mut need_update = false;

    {
        let mut state = data.state.lock().unwrap();

        if !state.enabled {
            return CallNextHookEx(None, code, wparam, lparam);
        }

        // Update cursor position for pen events
        if is_pen {
            state.cursor_x = x;
            state.cursor_y = y;
            state.cursor_visible = true;
        }

        // Handle system cursor hide/show
        if is_pen && msg == WM_LBUTTONDOWN && !PEN_DRAWING {
            ShowCursor(FALSE);
            PEN_DRAWING = true;
        }

        // Show cursor on any mouse up event
        if msg == WM_LBUTTONUP || msg == WM_RBUTTONUP || msg == WM_MBUTTONUP {
            if PEN_DRAWING {
                ShowCursor(TRUE);
                PEN_DRAWING = false;
            }
            state.cursor_visible = false;
            need_update = true;
        }

        let pressure = estimate_pressure(extra_info);
        width_scale = state.width_scale;

        // Pen down: sample background if inverse mode, otherwise use pen color
        if is_pen && msg == WM_LBUTTONDOWN {
            if state.inverse_enabled {
                pen_color = sample_screen_inverse(x, y);
            } else {
                pen_color = (state.pen_r, state.pen_g, state.pen_b);
            }
            unsafe { STROKE_COLOR = pen_color; }
            modeler_action = Some(ModelerAction::Begin);
            need_update = true;
        }

        // Pen drag: feed into modeler
        if is_pen && msg == WM_MOUSEMOVE && PEN_DRAWING {
            pen_color = unsafe { STROKE_COLOR };
            modeler_action = Some(ModelerAction::Move);
            need_update = true;
        }

        // Pen up: finalize through modeler
        if is_pen && msg == WM_LBUTTONUP {
            pen_color = unsafe { STROKE_COLOR };
            modeler_action = Some(ModelerAction::End);
            need_update = true;
        }

        // Lock released here
    }

    // --- Phase 2: Feed modeler and draw (no locks held) ---

    if let Some(action) = modeler_action {
        let pressure = estimate_pressure(extra_info);
        match action {
            ModelerAction::Begin => {
                crate::glaspen2_modeler_begin(pen_color.0, pen_color.1, pen_color.2, x, y, pressure, timestamp, width_scale);
            }
            ModelerAction::Move => {
                crate::glaspen2_modeler_move(x, y, pressure, timestamp, width_scale);
            }
            ModelerAction::End => {
                crate::glaspen2_modeler_end(x, y, pressure, timestamp, width_scale);
            }
        }
        draw_modeler_buffer(&data.surface, pen_color.0, pen_color.1, pen_color.2);
    }

    if need_update {
        overlay::update_overlay(hwnd);
    }

    // Swallow pen events so other apps don't see them
    if is_pen && (msg == WM_LBUTTONDOWN || msg == WM_MOUSEMOVE || msg == WM_LBUTTONUP) {
        return LRESULT(1);
    }

    // Non-pen mouse events pass through
    CallNextHookEx(None, code, wparam, lparam)
}

enum ModelerAction {
    Begin,
    Move,
    End,
}
